name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/cake-lambda-blog
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/cake-lambda-blog
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: test/cake-lambda-blog.Tests
    - name: Publish
      run: dotnet publish -c Release
      working-directory: src/cake-lambda-blog
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.LAMBDA_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.LAMBDA_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy static site to S3 bucket
      run: ls src/cake-lambda-blog/bin/Release/netcoreapp3.1/publish/
